### PR TITLE
4.17 update

### PR DESCRIPTION
**Pull request by metahusk**
I made most of the changes for 4.17 here. The animations and other files have been re-saved to stop the errors from reporting. The depreciated bp node was replaced. The plugin was updated to reflect the post 4.15  targetrules change.

Should the intermediate files be gitinored? Normally I gitignore them in my personal project. I went ahead and committed them because the directory was already present from previous commits.

### CODE REVIEW

**Comment by EverNewJoy** [comment]
@metahusk  Thank you for this! 

I will post about this soon :)

♥

Rama

**Comment by EverNewJoy** [comment]
Thank you again for this! 

Is it fully ready? Should I do the merge?

:)

Rama

**Comment by metahusk** [comment]
No problem. It didn't take long. You've done far more work on these things than I have. I just figured you've been busy. :)

I've had no problems with it. I tested it a few times and I'm using it in two projects. 

I think 4.18 enforces ReadOnlyTargetRules, correct?

I broke up the changes into separate commits for clarity. The binary asset files were just re-saved. There were a few depreciated node changes in the blueprints. Other than that, it was pretty straightforward.

**Comment by metahusk** [comment]
If you find anything wrong, let me know. I didn't do any special testing, if you happened to have some form of procedure. I just re-saved blueprints, updated some of the code, and made sure it threw no errors.

**Pull request merged**
